apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grocy.fullname" . }}-scheduled-snapshots
  labels:
    {{- include "grocy.labels" . | nindent 4 }}
data:
  snapshot-public.yaml: |-
    apiVersion: snapshot.storage.k8s.io/v1alpha1
    kind: VolumeSnapshot
    metadata:
      name: {{ include "grocy.fullname" . }}-public-snapshot
    spec:
      source:
        name: {{ include "grocy.fullname" . }}-public
        kind: PersistentVolumeClaim
  snapshot-data.yaml: |-
    apiVersion: snapshot.storage.k8s.io/v1alpha1
    kind: VolumeSnapshot
    metadata:
      name: {{ include "grocy.fullname" . }}-data-snapshot
    spec:
      source:
        name: {{ include "grocy.fullname" . }}-data
        kind: PersistentVolumeClaim

    