apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "grocy.serviceAccountName" . }}-create-snapshots
  labels:
    {{- include "grocy.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}  
rules:
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources:
      - volumesnapshots
    verbs:
      - get
      - create
      - list
