apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "grocy.serviceAccountName" . }}-create-snapshots
  labels:
    {{- include "grocy.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ include "grocy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: {{ include "grocy.serviceAccountName" . }}-create-snapshots
  apiGroup: rbac.authorization.k8s.io
