apiVersion: v1
kind: Service
metadata:
  name: {{ include "grocy.fullname" . }}
  labels:
    {{- include "grocy.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  clusterIP: None    
  selector:
    {{- include "grocy.selectorLabels" . | nindent 4 }}
